// Generated by CoffeeScript 1.6.3
(function() {
  describe('Sona', function() {
    var sona;
    sona = null;
    beforeEach(function() {
      return sona = new Sona([
        {
          url: 'assets/sample.mp3',
          id: 'sample'
        }, {
          url: 'assets/test.mp3',
          id: 'test'
        }, {
          url: 'assets/example.mp3',
          id: 'example'
        }
      ]);
    });
    it('should load data into a buffer object', function() {
      return sona.load(function() {
        return expect(Object.keys(sona.buffers).length).toBe(3);
      });
    });
    it('should execute a callback when data is loaded', function() {
      var spy;
      spy = {
        callback: function() {
          return alert('Loaded!');
        }
      };
      spyOn(spy, 'callback');
      sona.load(spy.callback);
      return expect(spy.callback).toHaveBeenCalled;
    });
    return it('should play a loaded sound', function() {
      return sona.load(function() {
        return expect(sona.play('sample')).not.toThrow();
      });
    });
  });

}).call(this);
