// Generated by CoffeeScript 1.6.3
(function() {
  var Sona;

  Sona = (function() {
    function Sona(sounds) {
      window.AudioContext = window.AudioContext || window.webkitAudioContext;
      this.supported = !!AudioContext;
      if (!this.supported) {
        return;
      }
      this.context = new AudioContext();
      this.sounds = sounds;
    }

    Sona.prototype.load = function(callback) {
      var request, sound,
        _this = this;
      if (!this.supported) {
        return;
      }
      this.buffers = this.buffers || {};
      sound = this.sounds.shift();
      request = new XMLHttpRequest();
      request.open('GET', sound.url, true);
      request.responseType = 'arraybuffer';
      request.onload = function() {
        return _this.context.decodeAudioData(request.response, function(buffer) {
          _this.buffers[sound.id] = buffer;
          if (_this.sounds.length) {
            return _this.load(callback);
          } else if (typeof callback === 'function') {
            return callback();
          }
        });
      };
      return request.send();
    };

    Sona.prototype.play = function(id) {
      var source;
      if (this.buffers[id] === void 0 || !this.supported) {
        return;
      }
      source = this.context.createBufferSource();
      source.buffer = this.buffers[id];
      source.connect(this.context.destination);
      return source.start(0);
    };

    return Sona;

  })();

  window.Sona = Sona;

}).call(this);
